apiVersion: v1
kind: Endpoints
metadata:
  namespace: victoriametrics
  name: ignite-metrics
  labels:
    app: ignite-metrics
subsets:
  - addresses:
    - ip: 10.0.1.11
      targetRef:
        kind: Node
        name: ignite1
    - ip: 10.0.1.12
      targetRef:
        kind: Node
        name: ignite2
    - ip: 10.0.1.13
      targetRef:
        kind: Node
        name: ignite3
    ports:
      - name: metrics
        port: 9000
        protocol: TCP
