{
 "title": "Ignite Overview",
 "tags": [ "ignite" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(cluster_Rebalanced{job=\"ignite-metrics\"}, instance)"
    }
   },
   {
    "name": "DataRegionSource",
    "label": "DataRegionSource",
    "query": {
     "query": "label_values({__name__=~\"io_dataregion_.*TotalAllocatedSize\"},__name__)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status for $node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{endpoint=\"metrics\", instance=\"$node\", job=\"ignite-metrics\"}"
    }
   ]
  },
  {
   "title": "Ignite heap memory used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sys_memory_heap_max{instance=\"$node\"} - sys_memory_heap_used{instance=\"$node\"})*100 / sys_memory_heap_max{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Ignite CPU load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys_CpuLoad{instance=\"$node\"} * 100"
    }
   ]
  },
  {
   "title": "Total Baseline Nodes",
   "type": "stat",
   "description": "Total baseline nodes count",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_TotalBaselineNodes{instance=\"$node\",job=\"ignite-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Baseline Nodes",
   "type": "stat",
   "description": "Active baseline nodes count",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_ActiveBaselineNodes{instance=\"$node\",job=\"ignite-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Baseline Nodes",
   "type": "timeseries",
   "description": "Active baseline nodes count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "cluster_ActiveBaselineNodes{instance=\"$node\",job=\"ignite-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sys_memory_heap_used{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sys_CpuLoad{instance=\"$node\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Region IO memory used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((io_dataregion_${DataRegionSource}_MaxSize{instance=\"$node\"} - io_dataregion_${DataRegionSource}_TotalAllocatedSize{instance=\"$node\"}) / 1024 / 1024 / 1024 * 100 / (io_dataregion_${DataRegionSource}_MaxSize{instance=\"$node\"} / 1024 / 1024 / 1024))",
     "legendFormat": "${DataRegionSource}"
    }
   ]
  },
  {
   "title": "Data Region IO memory used (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "io_dataregion_${DataRegionSource}_TotalAllocatedSize{instance=\"$node\"} / 1024 / 1024 / 1024",
     "legendFormat": "${DataRegionSource} allocated size"
    },
    {
     "expr": "io_dataregion_${DataRegionSource}_MaxSize{instance=\"$node\"} / 1024 / 1024 / 1024",
     "legendFormat": "${DataRegionSource} max size"
    }
   ]
  },
  { "title": "Cache & CacheGroup sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Local cache size",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_CacheSize{instance=\"$node\",job=\"ignite-metrics\"}",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Total Allocated Size",
   "type": "bargauge",
   "description": "Total size of memory allocated for group, in bytes.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cacheGroups_TotalAllocatedSize{instance=\"$node\",job=\"ignite-metrics\"}",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  { "title": "Cache operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Cache Gets",
   "type": "graph",
   "description": "The total number of gets to the cache.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "yaxes": [
    { "format": "r/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_CacheGets{instance=\"$node\",job=\"ignite-metrics\"}[1m])",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Puts",
   "type": "graph",
   "description": "The total number of puts to the cache.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "yaxes": [
    { "format": "r/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_CachePuts{instance=\"$node\",job=\"ignite-metrics\"}[1m])",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "description": "A miss is a get request that is not satisfied.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "yaxes": [
    { "format": "r/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_CacheMisses{instance=\"$node\",job=\"ignite-metrics\"}[1m])",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "The number of get requests that were satisfied by the cache",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(cache_CacheHits{instance=\"$node\",job=\"ignite-metrics\"}[1m])",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Off Heap Entries Count",
   "type": "graph",
   "description": "Offheap entries count.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ent/s" } },
   "yaxes": [
    { "format": "ent/s" }
   ],
   "targets": [
    {
     "expr": "rate(cache_OffHeapEntriesCount{instance=\"$node\",job=\"ignite-metrics\"}[1m])",
     "legendFormat": "{{cache_name}}"
    }
   ]
  }
 ]
}