global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']
    metric_relabel_configs:
      # --- cache ---
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(CacheSize)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(CacheSize)'
        replacement: '${1}_${3}'
        target_label: __name__
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(CacheHits)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(CacheHits)'
        replacement: '${1}_${3}'
        target_label: __name__
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(CacheGets)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(CacheGets)'
        replacement: '${1}_${3}'
        target_label: __name__
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(CachePuts)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(CachePuts)'
        replacement: '${1}_${3}'
        target_label: __name__
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(CacheMisses)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(CacheMisses)'
        replacement: '${1}_${3}'
        target_label: __name__
      - source_labels: [__name__]
        regex: "(cache)_(.+)_(OffHeapEntriesCount)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cache)_(.+)_(OffHeapEntriesCount)'
        replacement: '${1}_${3}'
        target_label: __name__
      # --- cacheGroups ----
      - source_labels: [__name__]
        regex: "(cacheGroups)_(.+)_(TotalAllocatedSize)"
        replacement: "$2"
        target_label: "cache_name"
      - source_labels: [__name__]
        regex: '(cacheGroups)_(.+)_(TotalAllocatedSize)'
        replacement: '${1}_${3}'
        target_label: __name__
